version: '3.8'

services:
  rabbitmq-backup:
    build:
      context: .
    volumes:
      - /data/GC/swimti-backup/rabbitmq-logs:/app/rabbitmq-logs
    restart: always
    container_name: rabbitmq-backup
    ports:
      - "20000:20000"